"""inital migrate

Revision ID: 745e63b5d917
Revises: 
Create Date: 2022-02-12 20:02:40.381440

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '745e63b5d917'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visitors')
    op.drop_table('multiple_choice')
    op.drop_table('record')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('record',
    sa.Column('sno', mysql.CHAR(length=20), nullable=False),
    sa.Column('user_number', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('ans1', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('ans2', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('ans3', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('ans4', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('ans5', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('score', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('multiple_choice',
    sa.Column('number', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('question', mysql.CHAR(length=50), nullable=True),
    sa.Column('option_A', mysql.CHAR(length=20), nullable=True),
    sa.Column('option_B', mysql.CHAR(length=20), nullable=True),
    sa.Column('option_C', mysql.CHAR(length=20), nullable=True),
    sa.Column('option_D', mysql.CHAR(length=20), nullable=True),
    sa.Column('right_option', mysql.CHAR(length=5), nullable=True),
    sa.Column('is_delete', mysql.BIT(length=1), nullable=True),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('visitors',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('age', mysql.TINYINT(unsigned=True), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('gender', mysql.ENUM('男', '女'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
