"""alter posts

Revision ID: a56c783a8aec
Revises: 88772727c146
Create Date: 2022-02-24 11:42:14.983350

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a56c783a8aec'
down_revision = '88772727c146'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Posts',
    sa.Column('rec_id', sa.Integer(), nullable=False),
    sa.Column('anther_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=50), nullable=True),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('rec_id')
    )
    op.create_index(op.f('ix_Posts_anther_id'), 'Posts', ['anther_id'], unique=False)
    op.create_index(op.f('ix_Posts_timestamp'), 'Posts', ['timestamp'], unique=False)
    op.drop_index('ix_Posts_anther_id', table_name='posts')
    op.drop_table('posts')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('rec_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('anther_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('title', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('body', mysql.VARCHAR(length=140), nullable=True),
    sa.PrimaryKeyConstraint('rec_id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_Posts_anther_id', 'posts', ['anther_id'], unique=False)
    op.drop_index(op.f('ix_Posts_timestamp'), table_name='Posts')
    op.drop_index(op.f('ix_Posts_anther_id'), table_name='Posts')
    op.drop_table('Posts')
    # ### end Alembic commands ###
